'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LogOut

    '''<summary>
    '''tbl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl1 As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''lblLoggedOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoggedOut As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblThanks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblThanks As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMashreq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMashreq As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnline As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrivacy1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrivacy1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPrivacy2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrivacy2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIdle1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdle1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIdle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdle2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTechQ1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTechQ1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTechQ2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTechQ2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTechQ3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTechQ3 As Global.System.Web.UI.WebControls.Label
End Class
